name: VirusTotal Scan

on:
  push:
    paths:
      - 'scripts/routermcs.sh' # Only runs when the script is actually updated
  release:
    types: [published]
  workflow_dispatch:

jobs:
  scan_and_update:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Grants the bot permission to push the updated README

    steps:
      - name: Checkout code
        uses: actions/checkout@v6.0.2

      - name: VirusTotal Scan
        uses: crazy-max/ghaction-virustotal@v4
        with:
          vt_api_key: ${{ secrets.VT_API_KEY }}
          files: |
            scripts/routermcs.sh

      - name: Update README with dynamic VT link
        run: |
          FILE_HASH=$(sha256sum scripts/routermcs.sh | awk '{print $1}')
          BADGE="[![VirusTotal Scan](https://github.com/benem3000/router_mcs_check/actions/workflows/virustotal.yml/badge.svg)](https://www.virustotal.com/gui/file/$FILE_HASH)"
          sed -i '/<!-- VT_BADGE_START -->/,/<!-- VT_BADGE_END -->/c\<!-- VT_BADGE_START -->\n'"$BADGE"'\n<!-- VT_BADGE_END -->' README.md

      - name: Commit and Push updated README
        uses: stefanzweifel/git-auto-commit-action@v7.1.0
        with:
          commit_message: "docs: auto-update VirusTotal link in README"
          file_pattern: 'README.md'
